#!/bin/sh
set -e

UDEV_RULES=/etc/udev/rules.d/99-logitech-hidpp.rules

ACTION=$1

# Source debconf library.
. /usr/share/debconf/confmodule

db_get keyleds/install_udev
INSTALL_UDEV="$RET"
db_stop

#DEBHELPER#

case "$ACTION" in
    configure)
        if [ "$INSTALL_UDEV" = "true" ]; then
            cp -f /usr/share/keyledsd/logitech.rules "$UDEV_RULES"
        else
            rm -f "$UDEV_RULES"
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
esac
