/* Keyleds -- Gaming keyboard tool
 * Copyright (C) 2017-2019 Julien Hartmann, juli1.hartmann@gmail.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef LIBKEYLEDS_EVENTCODE_H_A468C423
#define LIBKEYLEDS_EVENTCODE_H_A468C423

#include <linux/input.h>

namespace libkeyleds {

enum class EventCode : uint16_t {
    Invalid = KEY_RESERVED,
    Esc = KEY_ESC,
    KB1 = KEY_1,
    KB2 = KEY_2,
    KB3 = KEY_3,
    KB4 = KEY_4,
    KB5 = KEY_5,
    KB6 = KEY_6,
    KB7 = KEY_7,
    KB8 = KEY_8,
    KB9 = KEY_9,
    KB0 = KEY_0,
    Minus = KEY_MINUS,
    Equal = KEY_EQUAL,
    Backspace = KEY_BACKSPACE,
    Tab = KEY_TAB,
    Q = KEY_Q,
    W = KEY_W,
    E = KEY_E,
    R = KEY_R,
    T = KEY_T,
    Y = KEY_Y,
    U = KEY_U,
    I = KEY_I,
    O = KEY_O,
    P = KEY_P,
    LeftBrace = KEY_LEFTBRACE,
    RightBrace = KEY_RIGHTBRACE,
    Enter = KEY_ENTER,
    LeftCtrl = KEY_LEFTCTRL,
    A = KEY_A,
    S = KEY_S,
    D = KEY_D,
    F = KEY_F,
    G = KEY_G,
    H = KEY_H,
    J = KEY_J,
    K = KEY_K,
    L = KEY_L,
    Semicolon = KEY_SEMICOLON,
    Apostrophe = KEY_APOSTROPHE,
    Grave = KEY_GRAVE,
    LeftShift = KEY_LEFTSHIFT,
    BackSlash = KEY_BACKSLASH,
    Z = KEY_Z,
    X = KEY_X,
    C = KEY_C,
    V = KEY_V,
    B = KEY_B,
    N = KEY_N,
    M = KEY_M,
    Comma = KEY_COMMA,
    Dot = KEY_DOT,
    Slash = KEY_SLASH,
    RightShift = KEY_RIGHTSHIFT,
    KPAsterisk = KEY_KPASTERISK,
    LeftAlt = KEY_LEFTALT,
    Space = KEY_SPACE,
    CapsLock = KEY_CAPSLOCK,
    F1 = KEY_F1,
    F2 = KEY_F2,
    F3 = KEY_F3,
    F4 = KEY_F4,
    F5 = KEY_F5,
    F6 = KEY_F6,
    F7 = KEY_F7,
    F8 = KEY_F8,
    F9 = KEY_F9,
    F10 = KEY_F10,
    NumLock = KEY_NUMLOCK,
    ScrollLock = KEY_SCROLLLOCK,
    KP7 = KEY_KP7,
    KP8 = KEY_KP8,
    KP9 = KEY_KP9,
    KPMinus = KEY_KPMINUS,
    KP4 = KEY_KP4,
    KP5 = KEY_KP5,
    KP6 = KEY_KP6,
    KPPlus = KEY_KPPLUS,
    KP1 = KEY_KP1,
    KP2 = KEY_KP2,
    KP3 = KEY_KP3,
    KP0 = KEY_KP0,
    KPDot = KEY_KPDOT,
    Zenkakuhankaku = KEY_ZENKAKUHANKAKU,
    KB102nd = KEY_102ND,
    F11 = KEY_F11,
    F12 = KEY_F12,
    RO = KEY_RO,
    Katakana = KEY_KATAKANA,
    Hiragana = KEY_HIRAGANA,
    Henkan = KEY_HENKAN,
    KatakanaHiragana = KEY_KATAKANAHIRAGANA,
    Muhenkan = KEY_MUHENKAN,
    KPJPComma = KEY_KPJPCOMMA,
    KPEnter = KEY_KPENTER,
    RightCtrl = KEY_RIGHTCTRL,
    KPSlash = KEY_KPSLASH,
    SysRq = KEY_SYSRQ,
    RightAlt = KEY_RIGHTALT,
    LineFeed = KEY_LINEFEED,
    Home = KEY_HOME,
    Up = KEY_UP,
    PageUp = KEY_PAGEUP,
    Left = KEY_LEFT,
    Right = KEY_RIGHT,
    End = KEY_END,
    Down = KEY_DOWN,
    PageDown = KEY_PAGEDOWN,
    Insert = KEY_INSERT,
    Delete = KEY_DELETE,
    Macro = KEY_MACRO,
    Mute = KEY_MUTE,
    VolumeDown = KEY_VOLUMEDOWN,
    VolumeUp = KEY_VOLUMEUP,
    Power = KEY_POWER,
    KPEqual = KEY_KPEQUAL,
    KPPlusMinus = KEY_KPPLUSMINUS,
    Pause = KEY_PAUSE,
    Scale = KEY_SCALE,
    KPComma = KEY_KPCOMMA,
    Hangeul = KEY_HANGEUL,
    Hanguel = KEY_HANGUEL,
    Hanja = KEY_HANJA,
    Yen = KEY_YEN,
    LeftMeta = KEY_LEFTMETA,
    RightMeta = KEY_RIGHTMETA,
    Compose = KEY_COMPOSE,
    Stop = KEY_STOP,
    Again = KEY_AGAIN,
    Props = KEY_PROPS,
    Undo = KEY_UNDO,
    Front = KEY_FRONT,
    Copy = KEY_COPY,
    Open = KEY_OPEN,
    Paste = KEY_PASTE,
    Find = KEY_FIND,
    Cut = KEY_CUT,
    Help = KEY_HELP,
    Menu = KEY_MENU,
    Calc = KEY_CALC,
    Setup = KEY_SETUP,
    Sleep = KEY_SLEEP,
    WakeUp = KEY_WAKEUP,
    File = KEY_FILE,
    SendFile = KEY_SENDFILE,
    DeleteFile = KEY_DELETEFILE,
    XFer = KEY_XFER,
    Prog1 = KEY_PROG1,
    Prog2 = KEY_PROG2,
    WWW = KEY_WWW,
    MSDOS = KEY_MSDOS,
    Coffee = KEY_COFFEE,
    ScreenLock = KEY_SCREENLOCK,
    RotateDisplay = KEY_ROTATE_DISPLAY,
    Direction = KEY_DIRECTION,
    CycleWindows = KEY_CYCLEWINDOWS,
    Mail = KEY_MAIL,
    Bookmarks = KEY_BOOKMARKS,
    Computer = KEY_COMPUTER,
    Back = KEY_BACK,
    Forward = KEY_FORWARD,
    CloseCD = KEY_CLOSECD,
    EjectCD = KEY_EJECTCD,
    EjectCloseCD = KEY_EJECTCLOSECD,
    NextSong = KEY_NEXTSONG,
    PlayPause = KEY_PLAYPAUSE,
    PreviousSong = KEY_PREVIOUSSONG,
    StopCD = KEY_STOPCD,
    Record = KEY_RECORD,
    Rewind = KEY_REWIND,
    Phone = KEY_PHONE,
    ISO = KEY_ISO,
    Config = KEY_CONFIG,
    Homepage = KEY_HOMEPAGE,
    Refresh = KEY_REFRESH,
    Exit = KEY_EXIT,
    Move = KEY_MOVE,
    Edit = KEY_EDIT,
    ScrollUp = KEY_SCROLLUP,
    ScrollDown = KEY_SCROLLDOWN,
    KPLeftParen = KEY_KPLEFTPAREN,
    KPRightParen = KEY_KPRIGHTPAREN,
    New = KEY_NEW,
    Redo = KEY_REDO,
    F13 = KEY_F13,
    F14 = KEY_F14,
    F15 = KEY_F15,
    F16 = KEY_F16,
    F17 = KEY_F17,
    F18 = KEY_F18,
    F19 = KEY_F19,
    F20 = KEY_F20,
    F21 = KEY_F21,
    F22 = KEY_F22,
    F23 = KEY_F23,
    F24 = KEY_F24,
    PlayCD = KEY_PLAYCD,
    PauseCD = KEY_PAUSECD,
    Prog3 = KEY_PROG3,
    Prog4 = KEY_PROG4,
    Dashboard = KEY_DASHBOARD,
    Suspend = KEY_SUSPEND,
    Close = KEY_CLOSE,
    Play = KEY_PLAY,
    FastForward = KEY_FASTFORWARD,
    BassBoost = KEY_BASSBOOST,
    Print = KEY_PRINT,
    HP = KEY_HP,
    Camera = KEY_CAMERA,
    Sound = KEY_SOUND,
    Question = KEY_QUESTION,
    Email = KEY_EMAIL,
    Chat = KEY_CHAT,
    Search = KEY_SEARCH,
    Connect = KEY_CONNECT,
    Finance = KEY_FINANCE,
    Sport = KEY_SPORT,
    Shop = KEY_SHOP,
    AltErase = KEY_ALTERASE,
    Cancel = KEY_CANCEL,
    BrightnessDown = KEY_BRIGHTNESSDOWN,
    BrightnessUp = KEY_BRIGHTNESSUP,
    Media = KEY_MEDIA,
    SwitchVideoMode = KEY_SWITCHVIDEOMODE,
    KbdIllumToggle = KEY_KBDILLUMTOGGLE,
    KbdIllumDown = KEY_KBDILLUMDOWN,
    KbdIllumUp = KEY_KBDILLUMUP,
    Send = KEY_SEND,
    Reply = KEY_REPLY,
    ForwardMail = KEY_FORWARDMAIL,
    Save = KEY_SAVE,
    Documents = KEY_DOCUMENTS,
    Battery = KEY_BATTERY,
    Bluetooth = KEY_BLUETOOTH,
    WLAN = KEY_WLAN,
    UWB = KEY_UWB,
    Unknown = KEY_UNKNOWN,
    VideoNext = KEY_VIDEO_NEXT,
    VideoPrev = KEY_VIDEO_PREV,
    BrightnessCycle = KEY_BRIGHTNESS_CYCLE,
    BrightnessAuto = KEY_BRIGHTNESS_AUTO,
    BrightnessZero = KEY_BRIGHTNESS_ZERO,
    DisplayOff = KEY_DISPLAY_OFF,
    WWAN = KEY_WWAN,
    WiMax = KEY_WIMAX,
    RFKill = KEY_RFKILL,
    MicMute = KEY_MICMUTE
};

}

#endif
